### ISSUE TITLE
line 43: /usr/local/Library/ENV/4.3/sed: No such file or directory

### ISSUE THREAD

**Issue by philgruneich** [wilmoore/php-version#52]
Getting this error whenever my `.bash_profile` loads with `source $(brew --prefix php-version)/php-version.sh && php-version 5` probably due to `php-version 5`. Here a list of output you may find helpful.

```
17:40 $ source php-version/bug-report.sh | pbcopy
: command not found
/usr/local/Cellar/php56/5.6.23/bin/php-config: line 43: /usr/local/Library/ENV/4.3/sed: No such file or directory
```
```
17:35 $ source ~/.bash_profile
/usr/local/Cellar/php56/5.6.23/bin/php-config: line 43: /usr/local/Library/ENV/4.3/sed: No such file or directory
```
```
17:37 $ php-version
  5.4.45
  5.6.22
* 5.6.23
```
```
17:37 $ php-version 5
/usr/local/Cellar/php56/5.6.23/bin/php-config: line 43: /usr/local/Library/ENV/4.3/sed: No such file or directory
```
```
17:37 $ php-version 4
Sorry, but php-version was unable to find version '4' under ''.
```
```
17:39 $ tree -d -L 4 $(find $(brew --cellar) -maxdepth 1 -type d) | grep -E 'php[0-9]*$'
├── php54
│       │   └── php
│       │   └── php
│       ├── php
├── php56
│   │   │   └── php
│   │   │   └── php
│   │   ├── php
│   │   │   └── php
│       │   └── php
│       │   └── php
│       ├── php
│       │   └── php
/usr/local/Cellar/php54
    │   └── php
    │   └── php
    ├── php
/usr/local/Cellar/php56
│   │   └── php
│   │   └── php
│   ├── php
│   │   └── php
    │   └── php
    │   └── php
    ├── php
    │   └── php
```

**Comment by javian** [comment]
This error occurred after an update in brew where the php bottles had not been generated. This issue should be solved now.

**Comment by wilmoore** [comment]
Thanks @javian. In that case, I'll close this given that https://github.com/Homebrew/homebrew-php/issues/3352 has been closed.

**Comment by philgruneich** [comment]
I'm still getting it, even 17 days later. Is there any specific step I should take? Because I update Homebrew on a daily basis. I was forced to apply the solution from this issue https://github.com/Homebrew/homebrew-php/issues/3352#issuecomment-234489054, yet I suppose it should be more straightforward, correct?

**Comment by javian** [comment]
@philgruneich strange, the latest version of php56 is 5.6.25 - not .23 which you are using so something must be wrong on your system.

**Comment by philgruneich** [comment]
Your comment was very helpful, @javian, I did a `brew upgrade php56` and got the latest version. It is strange that my daily routine of `brew update` didn't get the job done before, but that's a topic for another issue. Thanks.

**Comment by emb03** [comment]
I am getting this error as well and have the latest version of php (5.6.25) installed. I ran `brew update` and it was `already up-to-date`. Any other suggestions to get rid of this error?

**Comment by javian** [comment]
@emb03 can you paste in the error ?

**Comment by emb03** [comment]
This fixed it. https://github.com/Homebrew/homebrew-php/issues/3352
I am not getting the error anymore. Apparently, it's a path issue.

**Comment by javian** [comment]
It works around the issue but your problem is that your homebrew is not updating itself since this specific was fixed way back. There's a different issue that's pending that involves sed but afaik with an updated homebrew this should not happen.

**Comment by emb03** [comment]
I updated homebrew and it happened again:
`Updated Homebrew from 985e772 to a148aa3.
Updated 1 tap (homebrew/core).
==> Updated Formulae
appscale-tools            consul                    elvish                    ios-deploy                logentries                pdnsrec                   scour                   
artifactory               dockutil                  fontconfig                libstrophe                minio                     ponyc                     serf                    
pow-m-dit302:www Ambi$ php-version
  5.6.11
  5.6.14
  5.6.25
pow-m-dit302:www Ambi$ php-version 5.6.11
/usr/local/Cellar/php56/5.6.11_2/bin/php-config: line 43: /usr/local/Library/ENV/4.3/sed: No such file or directory`

**Comment by javian** [comment]
That makes more sense thank you and explains what's going on. Since older versions aren't supported by homebrew the bottles would be compiled against the old codebase and the sed shim was moved a few months ago to a new location which means that an older version no longer finds sed in homebrew. We can't do anything to change that so you would have to manually edit the files with the incorrect paths. If you test with the 5.6.25 version you should see that it works.

**Comment by philgruneich** [comment]
@javian What is the new `sed` location?

**Comment by philgruneich** [comment]
I unapologetically changed the sed definition in php-config to the default sed from `which sed` and it works.
